server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grocery-shop
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: ${REDIRECT_URI}

management:
  endpoints:
    web:
      exposure:
        include: "*"

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
jwt:
  signerKey: ${JWT_SECRET}
  valid-access-duration: 3600
  valid-refresh-duration: 3600000