server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grocery-shop
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
jwt:
  signerKey: "hgHKoWb4RkgXz82ucDAD1cXQSyLPkHO+zcAnQxDpbQyNwHcywztLh4STeumzTA3k"
  valid-access-duration: 3600
  valid-refresh-duration: 3600000