server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-cp9gr1lds78s73chmh40-a.oregon-postgres.render.com:5432/grocery_9jlz
    username: grocery_9jlz_user
    password: 9to3vLOpeCDtInMMUDLK44X955aLXyhF
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
jwt:
  signerKey: "hgHKoWb4RkgXz82ucDAD1cXQSyLPkHO+zcAnQxDpbQyNwHcywztLh4STeumzTA3k"
  valid-access-duration: 3600
  valid-refresh-duration: 3600000